---
title: "STAT 534 - Lecture 24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.align= 'center')
knitr::opts_chunk$set(fig.height= 4)
knitr::opts_chunk$set(fig.width = 6)
```

### Modeling Point Patterns using NHPPs

- Statistical modeling depends on a sampling model for the data and the associated likelihood function. 
\vfill
- *Conditional on the number of points, $Num(D) = n$, the location density can be specified as:*

\vfill
- Then condidering the location and number of points simultaneously, we have
$$f(\boldsymbol{s}_1, \dots, \boldsymbol{s}_n, Num(D) = n) = \prod_i \frac{\lambda(\boldsymbol{s}_i)}{(\lambda(D))^n} \times$$
\vfill
\vfill
- *Finally, the likelihood is*
\vfill
\vfill
- Alternatively, consider a fine partition for $D$, then using the Poisson assumption, the likelihood is the product of the counts across the partitions.
$$\prod_l \exp(-\lambda(A_l))(\lambda(A_l))^{Num(A_l)}$$
As the grid becomes finer, $Num(A_l) \in \{0,1\}$.
\vfill
\newpage

- *The likelihood is a function of the entire intensity surface $\lambda(\boldsymbol{s})$.*
\vfill
\vfill
- __Discuss__: how could $\lambda(\boldsymbol{s})$ be obtained?

\vfill
- *There are two general approaches for modeling $\lambda(\boldsymbol{s})$:*

\vfill

- A simple, but "silly" example of a parametric form would be $\lambda(\boldsymbol{s}) = \sigma \lambda_0(\boldsymbol{s}).$ 
\vfill

- Suppose remoted-sensed covariate information is available on a grid. How might this be used for constructing $\lambda(\boldsymbol{s})$?
\vfill
- In general a parametric function $\lambda(\boldsymbol{s}; \theta)$ could be specified, but it would required a richly specified class that would need to be non-negative. A common approach for this type of problem is to use a set of basis functions such that $\lambda(\boldsymbol{s}; \theta) = \sum_k a_k g_k(\boldsymbol{s})$.
\vfill
- Sketch a set of basis functions to create a multimodal curve in 1D.\vfill
\vfill
\newpage

- *Sometimes a trend surface*
\vfill
\vfill
- The most common approach is to specify $\log(\lambda(\boldsymbol{s})) = X^t(\boldsymbol{s}) \gamma$.
\vfill
- Specifying covariates still requires integrating $\int_D\exp(X^t(\boldsymbol{s}) \gamma) d\boldsymbol{s}$, which is challenging as $X^t(\boldsymbol{s}$ is not often specified in a functional form.
\vfill
- *For a fine resolution*
\vfill
\vfill
- Now, considering $\lambda(\boldsymbol{s})$ through the non-parametric lens, 
\vfill
\vfill
- Suppose $\lambda(\boldsymbol{s}) = \exp(Z(\boldsymbol{s}))$ where $Z(\boldsymbol{s})$ is a realization from a spatial Gaussian process with mean $X^t(\boldsymbol{s}) \gamma$ and covariance function $\sigma^s \rho()$. 
\vfill
- The LGCP provides a prior for $\lambda(\boldsymbol{s})$. This can be written as $X^t(\boldsymbol{s}) \gamma + w(\boldsymbol{s})$ where $w(\boldsymbol{s}) = \log \lambda_0(\boldsymbol{s})$.
\vfill
\newpage

- __Discuss__: How to fit a model for a LGCP?

\vfill
- In the parametric setting, 
\vfill
\vfill
- In the non-parametric setting, 
\vfill
\vfill
- *Thus priors are needed*
\vfill
-In general algorithms for this type of data are computationally intensive.
\vfill
- Due to the challenges in modeling LGCP, the data is sometimes considered on a grid. Then the intensity for grid $i$ could be estimated as:
$$\log \lambda_i = X_i^t \beta + \phi_i.$$
However, the results can be sensitive to the grid specification.
\vfill





